/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all agents (newest first) */
        get: operations["listAgents"];
        put?: never;
        /** Create a new agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single agent */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        /** Delete an agent */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        /** Update an agent (partial) */
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/knowledge/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List knowledge buckets (with counts) */
        get: operations["listBuckets"];
        put?: never;
        /** Create a knowledge bucket */
        post: operations["createBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/buckets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a bucket plus its documents */
        get: operations["getBucket"];
        put?: never;
        post?: never;
        /** Delete a bucket (cascades documents + chunks) */
        delete: operations["deleteBucket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/buckets/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a bucket's documents */
        get: operations["listDocuments"];
        put?: never;
        /** Ingest a document (chunk → embed → store) */
        post: operations["ingestDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a document (cascades its chunks) */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the full retrieval pipeline against one or more buckets */
        post: operations["searchKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BuiltinToolFlags: {
            sendMessage?: boolean;
            deliverToAgent?: boolean;
            deliverToHuman?: boolean;
            endConversation?: boolean;
        };
        CustomToolDef: {
            name: string;
            description: string;
            schema: {
                [key: string]: unknown;
            };
            endpoint: string;
        };
        McpServerDef: {
            name: string;
            url: string;
            headers?: {
                [key: string]: string;
            };
        };
        HandoffRule: {
            when: {
                flag?: string;
                keywords?: string[];
            };
            assignTo: string;
        };
        GuardrailsConfig: {
            enabled?: boolean;
            scope?: string;
            refusal?: string;
        };
        KnowledgeConfig: {
            enabled?: boolean;
            bucketIds?: string[];
            topK?: number;
        };
        AgentDTO: {
            id: string;
            name: string;
            description: string;
            systemPrompt: string;
            model: string;
            temperature: number;
            isRoutable: boolean;
            isDefault: boolean;
            builtinTools: {
                sendMessage?: boolean;
                deliverToAgent?: boolean;
                deliverToHuman?: boolean;
                endConversation?: boolean;
            };
            customTools: {
                name: string;
                description: string;
                schema: {
                    [key: string]: unknown;
                };
                endpoint: string;
            }[];
            mcpServers: {
                name: string;
                url: string;
                headers?: {
                    [key: string]: string;
                };
            }[];
            handoffRules: {
                when: {
                    flag?: string;
                    keywords?: string[];
                };
                assignTo: string;
            }[];
            guardrails: {
                enabled?: boolean;
                scope?: string;
                refusal?: string;
            };
            knowledge: {
                enabled?: boolean;
                bucketIds?: string[];
                topK?: number;
            };
            createdAt: string;
            updatedAt: string;
        };
        AgentInput: {
            name?: string;
            description?: string;
            systemPrompt?: string;
            model?: string;
            temperature?: number;
            isRoutable?: boolean;
            isDefault?: boolean;
            builtinTools?: {
                sendMessage?: boolean;
                deliverToAgent?: boolean;
                deliverToHuman?: boolean;
                endConversation?: boolean;
            };
            customTools?: {
                name: string;
                description: string;
                schema: {
                    [key: string]: unknown;
                };
                endpoint: string;
            }[];
            mcpServers?: {
                name: string;
                url: string;
                headers?: {
                    [key: string]: string;
                };
            }[];
            handoffRules?: {
                when: {
                    flag?: string;
                    keywords?: string[];
                };
                assignTo: string;
            }[];
            guardrails?: {
                enabled?: boolean;
                scope?: string;
                refusal?: string;
            };
            knowledge?: {
                enabled?: boolean;
                bucketIds?: string[];
                topK?: number;
            };
        };
        /** @enum {string} */
        EmbeddingProviderId: "local" | "openai" | "voyage";
        Bucket: {
            id: string;
            name: string;
            description: string;
            /** @enum {string} */
            embeddingProvider: "local" | "openai" | "voyage";
            embeddingModel: string;
            embeddingDim: number;
            createdAt: string;
            documentCount?: number;
            chunkCount?: number;
        };
        RagDocument: {
            id: string;
            bucketId: string;
            title: string;
            source: string;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            chunkCount?: number;
        };
        RetrievedChunk: {
            id: string;
            documentId: string;
            bucketId: string;
            content: string;
            metadata: {
                [key: string]: unknown;
            };
            documentTitle: string;
            documentSource: string;
            score: number;
        };
        CreateBucketInput: {
            name: string;
            description?: string;
            /** @enum {string} */
            provider?: "local" | "openai" | "voyage";
            model?: string;
        };
        IngestDocumentInput: {
            title: string;
            source?: string;
            content: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        SearchInput: {
            bucketIds: string[];
            query: string;
            topK?: number;
            model?: string;
        };
        ErrorResponse: {
            error: string;
        };
        OkResponse: {
            ok: boolean;
        };
        AgentResponse: {
            agent: {
                id: string;
                name: string;
                description: string;
                systemPrompt: string;
                model: string;
                temperature: number;
                isRoutable: boolean;
                isDefault: boolean;
                builtinTools: {
                    sendMessage?: boolean;
                    deliverToAgent?: boolean;
                    deliverToHuman?: boolean;
                    endConversation?: boolean;
                };
                customTools: {
                    name: string;
                    description: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    endpoint: string;
                }[];
                mcpServers: {
                    name: string;
                    url: string;
                    headers?: {
                        [key: string]: string;
                    };
                }[];
                handoffRules: {
                    when: {
                        flag?: string;
                        keywords?: string[];
                    };
                    assignTo: string;
                }[];
                guardrails: {
                    enabled?: boolean;
                    scope?: string;
                    refusal?: string;
                };
                knowledge: {
                    enabled?: boolean;
                    bucketIds?: string[];
                    topK?: number;
                };
                createdAt: string;
                updatedAt: string;
            };
        };
        AgentsResponse: {
            agents: {
                id: string;
                name: string;
                description: string;
                systemPrompt: string;
                model: string;
                temperature: number;
                isRoutable: boolean;
                isDefault: boolean;
                builtinTools: {
                    sendMessage?: boolean;
                    deliverToAgent?: boolean;
                    deliverToHuman?: boolean;
                    endConversation?: boolean;
                };
                customTools: {
                    name: string;
                    description: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    endpoint: string;
                }[];
                mcpServers: {
                    name: string;
                    url: string;
                    headers?: {
                        [key: string]: string;
                    };
                }[];
                handoffRules: {
                    when: {
                        flag?: string;
                        keywords?: string[];
                    };
                    assignTo: string;
                }[];
                guardrails: {
                    enabled?: boolean;
                    scope?: string;
                    refusal?: string;
                };
                knowledge: {
                    enabled?: boolean;
                    bucketIds?: string[];
                    topK?: number;
                };
                createdAt: string;
                updatedAt: string;
            }[];
        };
        BucketResponse: {
            bucket: {
                id: string;
                name: string;
                description: string;
                /** @enum {string} */
                embeddingProvider: "local" | "openai" | "voyage";
                embeddingModel: string;
                embeddingDim: number;
                createdAt: string;
                documentCount?: number;
                chunkCount?: number;
            };
        };
        BucketsResponse: {
            buckets: {
                id: string;
                name: string;
                description: string;
                /** @enum {string} */
                embeddingProvider: "local" | "openai" | "voyage";
                embeddingModel: string;
                embeddingDim: number;
                createdAt: string;
                documentCount?: number;
                chunkCount?: number;
            }[];
        };
        BucketDetailResponse: {
            bucket: {
                id: string;
                name: string;
                description: string;
                /** @enum {string} */
                embeddingProvider: "local" | "openai" | "voyage";
                embeddingModel: string;
                embeddingDim: number;
                createdAt: string;
                documentCount?: number;
                chunkCount?: number;
            };
            documents: {
                id: string;
                bucketId: string;
                title: string;
                source: string;
                metadata: {
                    [key: string]: unknown;
                };
                createdAt: string;
                chunkCount?: number;
            }[];
        };
        DocumentsResponse: {
            documents: {
                id: string;
                bucketId: string;
                title: string;
                source: string;
                metadata: {
                    [key: string]: unknown;
                };
                createdAt: string;
                chunkCount?: number;
            }[];
        };
        DocumentResponse: {
            document: {
                id: string;
                bucketId: string;
                title: string;
                source: string;
                metadata: {
                    [key: string]: unknown;
                };
                createdAt: string;
                chunkCount?: number;
            };
        };
        SearchResponse: {
            results: {
                id: string;
                documentId: string;
                bucketId: string;
                content: string;
                metadata: {
                    [key: string]: unknown;
                };
                documentTitle: string;
                documentSource: string;
                score: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentInput"];
            };
        };
        responses: {
            /** @description Created agent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentInput"];
            };
        };
        responses: {
            /** @description Updated agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listBuckets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketsResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createBucket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBucketInput"];
            };
        };
        responses: {
            /** @description Created bucket */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bucket detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketDetailResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentsResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingestDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestDocumentInput"];
            };
        };
        responses: {
            /** @description Ingested document */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bucket not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchInput"];
            };
        };
        responses: {
            /** @description Retrieved chunks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
