/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sidecar health check
         * @description Returns service health including MySQL connectivity and build version. Responds 200 when MySQL is connected, 503 otherwise. Qdrant is probed (via its /readyz endpoint) and reported informationally.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 whenever the process is up and serving. No dependency probes — intended for the container runtime's restart decision so a transient MySQL/Qdrant blip does not kill a healthy instance.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Probes MySQL and Qdrant. Responds 200 when the instance can serve traffic, 503 when a critical dependency is unreachable. Intended for load-balancer/orchestrator readiness gating.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible chat completion
         * @description OpenAI Chat Completions facade over the multi-agent loop. Auth is a Bearer API key (resolves the tenant); `model` selects the entry agent by id; `stream:true` returns SSE chat.completion.chunk events, else a single chat.completion. Stateless — routing/escalation side-effects are delivered via the tenant's webhook, not the response.
         */
        post: operations["createChatCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the tenant's agents as OpenAI models */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one AI turn for a conversation
         * @description Runs the multi-agent orchestration loop for a conversation and streams a UIMessage stream (text/event-stream) back. Persistence and conversation-state changes are pushed to the chat service via its internal callback endpoint, so there is no JSON response body.
         */
        post: operations["chatTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agent-builder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one config-builder turn
         * @description Runs the (stateless) config-builder assistant and streams a UIMessage stream (text/event-stream): plain text plus `config-proposal` and `knowledge-seed` data parts the admin UI folds into an editable draft. Nothing is persisted — the draft is saved via /agents.
         */
        post: operations["agentBuilderTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all agents (newest first) */
        get: operations["listAgents"];
        put?: never;
        /** Create a new agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single agent */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        /** Delete an agent */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        /** Update an agent (partial) */
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/knowledge/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List knowledge buckets (with counts) */
        get: operations["listBuckets"];
        put?: never;
        /** Create a knowledge bucket */
        post: operations["createBucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/buckets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a bucket plus its documents */
        get: operations["getBucket"];
        put?: never;
        post?: never;
        /** Delete a bucket (cascades documents + chunks) */
        delete: operations["deleteBucket"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/buckets/{id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a bucket's documents */
        get: operations["listDocuments"];
        put?: never;
        /** Ingest a document (chunk → embed → store) */
        post: operations["ingestDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/buckets/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest an uploaded file (extract → chunk → embed → store)
         * @description Upload a file (PDF, DOCX, PPTX, XLSX, HTML, Markdown, CSV, text, image) as multipart/form-data. The file is converted to text, chunked with an auto-detected strategy, embedded with the bucket's provider, and stored.
         */
        post: operations["ingestFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a document (cascades its chunks) */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the catalog of supported providers and models
         * @description Returns the static provider and model catalog for this sidecar. Includes all supported chat providers (Anthropic, DeepSeek) and embedding providers (OpenAI, Voyage, Local). No authentication required — the catalog contains provider/model metadata only, no secrets or tenant data.
         */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the full retrieval pipeline against one or more buckets */
        post: operations["searchKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/test-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a BYOK embedding key for a provider (no data stored)
         * @description Runs one minimal embedding round-trip with the inline X-Embedding-Key header against the named provider. Nothing is persisted and the key is never logged. Used by the AI Config 'Test' button.
         */
        post: operations["testEmbeddingKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BuiltinToolFlags: {
            sendMessage?: boolean;
            deliverToAgent?: boolean;
            deliverToHuman?: boolean;
            endConversation?: boolean;
        };
        CustomToolDef: {
            name: string;
            description: string;
            schema: {
                [key: string]: unknown;
            };
            endpoint: string;
        };
        McpServerDef: {
            name: string;
            url: string;
            headers?: {
                [key: string]: string;
            };
        };
        HandoffRule: {
            when: {
                flag?: string;
                keywords?: string[];
            };
            assignTo: string;
        };
        GuardrailsConfig: {
            enabled?: boolean;
            scope?: string;
            refusal?: string;
        };
        KnowledgeConfig: {
            enabled?: boolean;
            bucketIds?: string[];
            topK?: number;
        };
        AgentDTO: {
            id: string;
            name: string;
            description: string;
            systemPrompt: string;
            model: string;
            temperature: number;
            maxTokens: number;
            isRoutable: boolean;
            isDefault: boolean;
            builtinTools: {
                sendMessage?: boolean;
                deliverToAgent?: boolean;
                deliverToHuman?: boolean;
                endConversation?: boolean;
            };
            customTools: {
                name: string;
                description: string;
                schema: {
                    [key: string]: unknown;
                };
                endpoint: string;
            }[];
            mcpServers: {
                name: string;
                url: string;
                headers?: {
                    [key: string]: string;
                };
            }[];
            handoffRules: {
                when: {
                    flag?: string;
                    keywords?: string[];
                };
                assignTo: string;
            }[];
            guardrails: {
                enabled?: boolean;
                scope?: string;
                refusal?: string;
            };
            knowledge: {
                enabled?: boolean;
                bucketIds?: string[];
                topK?: number;
            };
            createdAt: string;
            updatedAt: string;
        };
        AgentInput: {
            name?: string;
            description?: string;
            systemPrompt?: string;
            model?: string;
            temperature?: number;
            maxTokens?: number;
            isRoutable?: boolean;
            isDefault?: boolean;
            builtinTools?: {
                sendMessage?: boolean;
                deliverToAgent?: boolean;
                deliverToHuman?: boolean;
                endConversation?: boolean;
            };
            customTools?: {
                name: string;
                description: string;
                schema: {
                    [key: string]: unknown;
                };
                endpoint: string;
            }[];
            mcpServers?: {
                name: string;
                url: string;
                headers?: {
                    [key: string]: string;
                };
            }[];
            handoffRules?: {
                when: {
                    flag?: string;
                    keywords?: string[];
                };
                assignTo: string;
            }[];
            guardrails?: {
                enabled?: boolean;
                scope?: string;
                refusal?: string;
            };
            knowledge?: {
                enabled?: boolean;
                bucketIds?: string[];
                topK?: number;
            };
        };
        /** @enum {string} */
        EmbeddingProviderId: "local" | "openai" | "voyage" | "voyage-multimodal";
        Bucket: {
            id: string;
            name: string;
            description: string;
            /** @enum {string} */
            embeddingProvider: "local" | "openai" | "voyage" | "voyage-multimodal";
            embeddingModel: string;
            embeddingDim: number;
            createdAt: string;
            documentCount?: number;
            chunkCount?: number;
        };
        RagDocument: {
            id: string;
            bucketId: string;
            title: string;
            source: string;
            metadata: {
                [key: string]: unknown;
            };
            createdAt: string;
            chunkCount?: number;
        };
        RetrievedChunk: {
            id: string;
            documentId: string;
            bucketId: string;
            content: string;
            metadata: {
                [key: string]: unknown;
            };
            documentTitle: string;
            documentSource: string;
            score: number;
        };
        CreateBucketInput: {
            name: string;
            description?: string;
            /** @enum {string} */
            provider?: "local" | "openai" | "voyage" | "voyage-multimodal" | "auto";
            model?: string;
        };
        /** @enum {string} */
        ChunkStrategy: "auto" | "markdown" | "recursive" | "paragraph" | "sentence";
        IngestDocumentInput: {
            title: string;
            source?: string;
            content: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            chunkStrategy?: "auto" | "markdown" | "recursive" | "paragraph" | "sentence";
        };
        IngestFileInput: {
            title?: string;
            source?: string;
            /** @enum {string} */
            chunkStrategy?: "auto" | "markdown" | "recursive" | "paragraph" | "sentence";
        };
        SearchInput: {
            bucketIds: string[];
            query: string;
            topK?: number;
            model?: string;
        };
        ChatUIMessageInput: {
            id?: string;
            role: string;
            parts: {
                [key: string]: unknown;
            }[];
            metadata?: {
                [key: string]: unknown;
            };
        };
        ChatTurnInput: {
            tenantId: string;
            conversationId: string;
            agentId: string;
            routingFlag?: string | null;
            messages: {
                id?: string;
                role: string;
                parts: {
                    [key: string]: unknown;
                }[];
                metadata?: {
                    [key: string]: unknown;
                };
            }[];
        };
        AgentBuilderInput: {
            messages: {
                id?: string;
                role: string;
                parts: {
                    [key: string]: unknown;
                }[];
                metadata?: {
                    [key: string]: unknown;
                };
            }[];
            currentDraft?: {
                name?: string;
                description?: string;
                systemPrompt?: string;
                model?: string;
                temperature?: number;
                maxTokens?: number;
                isRoutable?: boolean;
                isDefault?: boolean;
                builtinTools?: {
                    sendMessage?: boolean;
                    deliverToAgent?: boolean;
                    deliverToHuman?: boolean;
                    endConversation?: boolean;
                };
                customTools?: {
                    name: string;
                    description: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    endpoint: string;
                }[];
                mcpServers?: {
                    name: string;
                    url: string;
                    headers?: {
                        [key: string]: string;
                    };
                }[];
                handoffRules?: {
                    when: {
                        flag?: string;
                        keywords?: string[];
                    };
                    assignTo: string;
                }[];
                guardrails?: {
                    enabled?: boolean;
                    scope?: string;
                    refusal?: string;
                };
                knowledge?: {
                    enabled?: boolean;
                    bucketIds?: string[];
                    topK?: number;
                };
            } | null;
            editing?: boolean;
        };
        ErrorResponse: {
            error: string;
        };
        OkResponse: {
            ok: boolean;
        };
        AgentResponse: {
            agent: {
                id: string;
                name: string;
                description: string;
                systemPrompt: string;
                model: string;
                temperature: number;
                maxTokens: number;
                isRoutable: boolean;
                isDefault: boolean;
                builtinTools: {
                    sendMessage?: boolean;
                    deliverToAgent?: boolean;
                    deliverToHuman?: boolean;
                    endConversation?: boolean;
                };
                customTools: {
                    name: string;
                    description: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    endpoint: string;
                }[];
                mcpServers: {
                    name: string;
                    url: string;
                    headers?: {
                        [key: string]: string;
                    };
                }[];
                handoffRules: {
                    when: {
                        flag?: string;
                        keywords?: string[];
                    };
                    assignTo: string;
                }[];
                guardrails: {
                    enabled?: boolean;
                    scope?: string;
                    refusal?: string;
                };
                knowledge: {
                    enabled?: boolean;
                    bucketIds?: string[];
                    topK?: number;
                };
                createdAt: string;
                updatedAt: string;
            };
        };
        AgentsResponse: {
            agents: {
                id: string;
                name: string;
                description: string;
                systemPrompt: string;
                model: string;
                temperature: number;
                maxTokens: number;
                isRoutable: boolean;
                isDefault: boolean;
                builtinTools: {
                    sendMessage?: boolean;
                    deliverToAgent?: boolean;
                    deliverToHuman?: boolean;
                    endConversation?: boolean;
                };
                customTools: {
                    name: string;
                    description: string;
                    schema: {
                        [key: string]: unknown;
                    };
                    endpoint: string;
                }[];
                mcpServers: {
                    name: string;
                    url: string;
                    headers?: {
                        [key: string]: string;
                    };
                }[];
                handoffRules: {
                    when: {
                        flag?: string;
                        keywords?: string[];
                    };
                    assignTo: string;
                }[];
                guardrails: {
                    enabled?: boolean;
                    scope?: string;
                    refusal?: string;
                };
                knowledge: {
                    enabled?: boolean;
                    bucketIds?: string[];
                    topK?: number;
                };
                createdAt: string;
                updatedAt: string;
            }[];
        };
        BucketResponse: {
            bucket: {
                id: string;
                name: string;
                description: string;
                /** @enum {string} */
                embeddingProvider: "local" | "openai" | "voyage" | "voyage-multimodal";
                embeddingModel: string;
                embeddingDim: number;
                createdAt: string;
                documentCount?: number;
                chunkCount?: number;
            };
        };
        BucketsResponse: {
            buckets: {
                id: string;
                name: string;
                description: string;
                /** @enum {string} */
                embeddingProvider: "local" | "openai" | "voyage" | "voyage-multimodal";
                embeddingModel: string;
                embeddingDim: number;
                createdAt: string;
                documentCount?: number;
                chunkCount?: number;
            }[];
        };
        BucketDetailResponse: {
            bucket: {
                id: string;
                name: string;
                description: string;
                /** @enum {string} */
                embeddingProvider: "local" | "openai" | "voyage" | "voyage-multimodal";
                embeddingModel: string;
                embeddingDim: number;
                createdAt: string;
                documentCount?: number;
                chunkCount?: number;
            };
            documents: {
                id: string;
                bucketId: string;
                title: string;
                source: string;
                metadata: {
                    [key: string]: unknown;
                };
                createdAt: string;
                chunkCount?: number;
            }[];
        };
        DocumentsResponse: {
            documents: {
                id: string;
                bucketId: string;
                title: string;
                source: string;
                metadata: {
                    [key: string]: unknown;
                };
                createdAt: string;
                chunkCount?: number;
            }[];
        };
        DocumentResponse: {
            document: {
                id: string;
                bucketId: string;
                title: string;
                source: string;
                metadata: {
                    [key: string]: unknown;
                };
                createdAt: string;
                chunkCount?: number;
            };
        };
        SearchResponse: {
            results: {
                id: string;
                documentId: string;
                bucketId: string;
                content: string;
                metadata: {
                    [key: string]: unknown;
                };
                documentTitle: string;
                documentSource: string;
                score: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description true when all critical dependencies are connected */
                        ok: boolean;
                        /** @description npm package version */
                        version: string;
                        /**
                         * @description MySQL connectivity status
                         * @enum {string}
                         */
                        mysql: "connected" | "error";
                        /**
                         * @description Qdrant connectivity status
                         * @enum {string}
                         */
                        qdrant: "ok" | "error" | "not configured";
                    };
                };
            };
            /** @description Service is degraded (MySQL unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        version: string;
                        /** @enum {string} */
                        mysql: "connected" | "error";
                        /** @enum {string} */
                        qdrant: "ok" | "error" | "not configured";
                    };
                };
            };
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        /** @enum {string} */
                        status: "live";
                        version: string;
                    };
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready to serve traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        version: string;
                        /** @enum {string} */
                        mysql: "ok" | "error";
                        /** @enum {string} */
                        qdrant: "ok" | "error" | "not configured";
                    };
                };
            };
            /** @description Service is not ready (a critical dependency is unreachable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                        version: string;
                        /** @enum {string} */
                        mysql: "ok" | "error";
                        /** @enum {string} */
                        qdrant: "ok" | "error" | "not configured";
                    };
                };
            };
        };
    };
    createChatCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Entry agent id. */
                    model: string;
                    messages: {
                        role: string;
                        content?: string;
                    }[];
                    stream?: boolean;
                    user?: string;
                    conversation_id?: string;
                };
            };
        };
        responses: {
            /** @description A chat.completion (JSON) or chat.completion.chunk stream (SSE). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Model (agent) not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An OpenAI model list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chatTurn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatTurnInput"];
            };
        };
        responses: {
            /** @description A UIMessage stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No agent assigned */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    agentBuilderTurn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentBuilderInput"];
            };
        };
        responses: {
            /** @description A UIMessage stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentInput"];
            };
        };
        responses: {
            /** @description Created agent */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentInput"];
            };
        };
        responses: {
            /** @description Updated agent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listBuckets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buckets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketsResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createBucket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBucketInput"];
            };
        };
        responses: {
            /** @description Created bucket */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bucket detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BucketDetailResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteBucket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentsResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingestDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestDocumentInput"];
            };
        };
        responses: {
            /** @description Ingested document */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bucket not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ingestFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    title?: string;
                    source?: string;
                    chunkStrategy?: components["schemas"]["ChunkStrategy"];
                };
            };
        };
        responses: {
            /** @description Ingested document */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Missing/invalid file or fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Bucket not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No extractable text in file */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider and model catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchInput"];
            };
        };
        responses: {
            /** @description Retrieved chunks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description RAG store unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    testEmbeddingKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Embedding provider to validate the key against.
                     * @enum {string}
                     */
                    provider: "openai" | "voyage" | "voyage-multimodal";
                };
            };
        };
        responses: {
            /** @description Key accepted by the provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing key or unsupported provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Provider rejected the key or was unreachable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
